### PR TITLE
Address to link

### LINKED ISSUE #5: Make addresses clickable and have them open the address in Google Maps in a new tab

### PR DESCRIPTION
**Pull request by adgai19**
work on #5 
kindly review the changes and tell me if I need to improve anything

### CODE REVIEW

**Comment by jvsinghk** [comment]
@adgai19  have reviewed the changes. Looks good to me. Can you add the gif in the PR? Showing the redirection of the Address to the Google Map Address page.

**Comment by adgai19** [comment]
Hnet-image(2)
@jvsinghk

**Comment by jvsinghk** [comment]
@adgai19 Great, Thanks for Contributing. Happy Hacking Hacktoberfest, Stay Connected, and Safe.

**Review by jvsinghk — COMMENTED** [review]
@adgai19 Great, Thanks for Contributing.

**Pull request merged**
